export {default as User } from './user'
export {default as Game } from './game'
export {default as Char} from './char'
export {default as Skill} from './skill'
export {default as AttrA} from './attrA'
export {default as AttrB} from './attrB'